sudo: required

language: cpp

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y curl
  - docker build -t ble-micro .

install: true

script:
  - docker run --rm -u $(id -u):$(id -g) -v $(pwd)/test:/usr/src/app ble-micro

after_success:
  - ./scripts/docker-trigger.sh
